controller_list:
  - name: multi_dof_joint_trajectory_action
    type: MultiDofFollowJointTrajectory
    default: true
    joints:
      - virtual_joint
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - palm_riser
      - palm_left_finger
      - left_finger_tip
      - palm_right_finger
      - right_finger_tip
