controller_list:
  - name: multi_dof_joint_trajectory_action
    type: MultiDofFollowJointTrajectory
    default: true
    joints:
      - virtual_joint
  - name: gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - palm_left_finger
      - left_finger_tip
      - palm_right_finger
      - right_finger_tip
