controller_list:
  - name: fake_Quad_base_controller
    joints:
      - virtual_joint
  - name: fake_end_gripper_controller
    joints:
      - palm_left_finger
      - left_finger_tip
      - palm_right_finger
      - right_finger_tip